
include /etc/nginx/includes/8g.conf;

if ($is_forbidden_method) { return 403; }
if ($is_bad_bot) { return 403; }
if ($is_bad_request) { return 403; }

 
location = /favicon.ico {
    log_not_found off;
    access_log off;
}  

location ~ /\.git {
    deny all;
}

location ~* ^/wp-includes/.*\.php$ {
    deny all;
}

location = /xmlrpc.php {
    deny all;
}

location ~* ^/wp-content/uploads/.*\.php$ {
    deny all;
}

