[filemanager-auth]
enabled   = true
filter    = filemanager-auth
backend   = systemd

# ambil log dari service filebrowser
journalmatch = _SYSTEMD_UNIT=filebrowser.service

port      = 2222
maxretry  = 10
findtime  = 10m
bantime   = 10m

banaction = iptables-allports
