[phpmyadmin-auth]
enabled  = true
filter   = phpmyadmin-auth
backend  = auto

logpath  = /home/*/logs/nginx/access.log
port     = http,https

maxretry = 5
findtime = 5m
bantime  = 30m

banaction = iptables-allports